apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: jellyfin
spec:
  secretName: jellyfin-tls
  dnsNames:
    - jellyfin.omv.mousses.xyz
  issuerRef:
    name: letsencrypt-production-cloudflare
    kind: ClusterIssuer
    group: cert-manager.io
