apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage-class.yaml
  - persistent-volumes.yaml
  - persistent-volume-claims.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - certificate-staging.yaml
  - certificate.yaml
  - networkpolicy.yaml
