apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jellyfin-local
  labels:
    app.kubernetes.io/part-of: jellyfin
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jellyfin-media-local
  labels:
    app.kubernetes.io/part-of: jellyfin
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
