apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage-class.yaml
  - persistent-volumes.yaml
  - helmchart-kube-prometheus-stack.yaml
  - helmchart-loki.yaml
  - helmchart-alloy.yaml
  - certificate.yaml
  - ingress.yaml
  - ../_shared/ingress-security
  - ../_shared/network-policy/baseline
  - ../_shared/network-policy/dns-egress
  - networkpolicy.yaml
patches:
  - target:
      group: traefik.io
      version: v1alpha1
      kind: Middleware
      name: security-headers
    patch: |-
      - op: add
        path: /metadata/namespace
        value: monitoring
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: default-deny-all
    patch: |-
      - op: add
        path: /metadata/namespace
        value: monitoring
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: allow-dns-egress
    patch: |-
      - op: add
        path: /metadata/namespace
        value: monitoring
