apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-prometheus
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: monitoring-local
  local:
    path: /filesystem/k3s/data/monitoring/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - openmediavault
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-alertmanager
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/part-of: monitoring
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: monitoring-local
  local:
    path: /filesystem/k3s/data/monitoring/alertmanager
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - openmediavault
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-grafana
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: monitoring-local
  local:
    path: /filesystem/k3s/data/monitoring/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - openmediavault
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-loki
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: loki
    app.kubernetes.io/part-of: monitoring
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: monitoring-local
  local:
    path: /filesystem/k3s/data/monitoring/loki
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - openmediavault
