apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-staging
  namespace: n8n
spec:
  secretName: n8n-tls-staging
  dnsNames:
    - n8n.omv.mousses.xyz
  issuerRef:
    name: letsencrypt-staging-cloudflare
    kind: ClusterIssuer
    group: cert-manager.io
