apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: n8n-local
  labels:
    app.kubernetes.io/part-of: n8n
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
