apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: librechat-local
  labels:
    app.kubernetes.io/part-of: librechat
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
