apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: authentik-local
  volumeName: authentik-postgres
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-data
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: authentik-local
  volumeName: authentik-data
  resources:
    requests:
      storage: 5Gi
