apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: litellm-admin
  namespace: litellm
spec:
  secretName: litellm-admin-tls
  dnsNames:
    - admin.ai.omv.mousses.xyz
  issuerRef:
    name: letsencrypt-production-cloudflare
    kind: ClusterIssuer
    group: cert-manager.io
