apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-postgres
  namespace: litellm
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: litellm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: litellm-local
  volumeName: litellm-postgres
  resources:
    requests:
      storage: 10Gi
