apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-staging
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/part-of: immich
spec:
  secretName: immich-tls-staging
  issuerRef:
    name: letsencrypt-staging-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - photos.omv.mousses.xyz
