apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/part-of: immich
data:
  IMMICH_VERSION: "v2"
  UPLOAD_LOCATION: /data
  DB_HOSTNAME: database
  DB_PORT: "5432"
  DB_USERNAME: postgres
  DB_DATABASE_NAME: immich
  REDIS_HOSTNAME: redis
  REDIS_PORT: "6379"
  MACHINE_LEARNING_URL: http://immich-machine-learning:3003
