apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: library
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: immich-local
  volumeName: immich-library
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: immich-local
  volumeName: immich-postgres
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: machine-learning
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: immich-local
  volumeName: immich-model-cache
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-external-photos
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: external-photos
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: immich-external-local
  volumeName: immich-external-photos
  resources:
    requests:
      storage: 1Ti
