apiVersion: v1
kind: PersistentVolume
metadata:
  name: searxng-cache
  labels:
    app.kubernetes.io/name: searxng
    app.kubernetes.io/part-of: searxng
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: searxng-local
  local:
    path: /filesystem/k3s/data/searxng/cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - openmediavault
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: searxng-valkey
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: searxng
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: searxng-local
  local:
    path: /filesystem/k3s/data/searxng/valkey
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - openmediavault
