apiVersion: v1
kind: Service
metadata:
  name: searxng
  namespace: searxng
  labels:
    app.kubernetes.io/name: searxng
    app.kubernetes.io/part-of: searxng
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: searxng
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: searxng
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: searxng
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: valkey
  ports:
    - name: valkey
      port: 6379
      targetPort: valkey
      protocol: TCP
