apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
  namespace: searxng
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: searxng
spec:
  serviceName: valkey
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: valkey
        app.kubernetes.io/part-of: searxng
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/hostname: openmediavault
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: valkey
          image: docker.io/valkey/valkey@sha256:d1cc70645bbcef743615463a2fa4616e841407545e18f560aed0c49671a90147
          imagePullPolicy: IfNotPresent
          args:
            - valkey-server
            - --save
            - "30"
            - "1"
            - --loglevel
            - warning
          ports:
            - name: valkey
              containerPort: 6379
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: valkey-data
              mountPath: /data
      volumes:
        - name: valkey-data
          persistentVolumeClaim:
            claimName: searxng-valkey
      terminationGracePeriodSeconds: 30
