apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kiwix-media-local
  labels:
    app.kubernetes.io/part-of: kiwix
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
