apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crafty
resources:
  - namespace.yaml
  - storage-class.yaml
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - service.yaml
  - servers-transport.yaml
  - ingress.yaml
  - ../_shared/ingress-security
  - certificate-staging.yaml
  - certificate.yaml
  - ../_shared/network-policy/baseline
  - networkpolicy.yaml
