apiVersion: v1
kind: PersistentVolume
metadata:
  name: crafty-data
  labels:
    app.kubernetes.io/name: crafty
    app.kubernetes.io/part-of: crafty
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: crafty-local
  local:
    path: /filesystem/minecraft
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - openmediavault
