apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: text2shop
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ../_shared/ingress-security
  - certificate.yaml
  - ../_shared/network-policy/baseline
  - networkpolicy.yaml
