apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: board-games
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - migration-job.yaml
  - api.yaml
  - web.yaml
  - ingress.yaml
  - ../_shared/ingress-security
  - certificate.yaml
  - certificate-staging.yaml
  - ../_shared/network-policy/baseline
  - networkpolicy.yaml
