apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: it-tools-staging
  namespace: it-tools
spec:
  secretName: it-tools-tls-staging
  dnsNames:
    - it-tools.omv.mousses.xyz
  issuerRef:
    name: letsencrypt-staging-cloudflare
    kind: ClusterIssuer
    group: cert-manager.io
