apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-routes
resources:
  - namespace.yaml
  - services.yaml
  - ingressroute.yaml
  - certificate-staging.yaml
  - certificate.yaml
