apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: syncthing
  namespace: syncthing
  labels:
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/part-of: syncthing
spec:
  secretName: syncthing-tls
  dnsNames:
    - sync.omv.mousses.xyz
  issuerRef:
    name: letsencrypt-production-cloudflare
    kind: ClusterIssuer
    group: cert-manager.io

