apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-config
  labels:
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: syncthing
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: syncthing-local
  local:
    path: /filesystem/k3s/data/syncthing/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - openmediavault
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-music
  labels:
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/component: music
    app.kubernetes.io/part-of: syncthing
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: syncthing-media-local
  local:
    path: /filesystem/Media/Media/Music
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - openmediavault

