apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx
resources:
  - namespace.yaml
  - storage-class.yaml
  - persistent-volumes.yaml
  - persistent-volume-claims.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - dependencies.yaml
  - paperless.yaml
  - integrations.yaml
  - certificates.yaml
  - ingress.yaml
  - ../_shared/ingress-security
  - ../_shared/network-policy/baseline
  - ../_shared/network-policy/dns-egress
  - networkpolicy.yaml
