apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-data
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/part-of: open-webui
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: open-webui-local
  local:
    path: /filesystem/k3s/data/open-webui
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - openmediavault
