apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: open-webui-local
  labels:
    app.kubernetes.io/part-of: open-webui
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
