apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-agent-server
  labels:
    app.kubernetes.io/name: minecraft-agent
    app.kubernetes.io/part-of: minecraft-agent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minecraft-agent-local
  volumeName: minecraft-agent-server
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-agent-runs
  labels:
    app.kubernetes.io/name: minecraft-agent
    app.kubernetes.io/part-of: minecraft-agent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minecraft-agent-local
  volumeName: minecraft-agent-runs
  resources:
    requests:
      storage: 20Gi
