apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-agent-server
  labels:
    app.kubernetes.io/name: minecraft-agent
    app.kubernetes.io/part-of: minecraft-agent
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minecraft-agent-local
  local:
    path: /filesystem/k3s/data/minecraft-agent/server
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - openmediavault
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-agent-runs
  labels:
    app.kubernetes.io/name: minecraft-agent
    app.kubernetes.io/part-of: minecraft-agent
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minecraft-agent-local
  local:
    path: /filesystem/k3s/data/minecraft-agent/runs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - openmediavault
